export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

export const FETCH_USER_LISTS = "FETCH_USER_LISTS";
export const CLEAR_USER_LISTS = "CLEAR_USER_LISTS";

export const FETCH_SUBSCRIBERS = "FETCH_SUBSCRIBERS";
export const CLEAR_SUBSCRIBERS = "CLEAR_SUBSCRIBERS";

export const FETCH_TEMPLATES = "FETCH_TEMPLATES";
export const CLEAR_TEMPLATES = "CLEAR_TEMPLATES";

export const FETCH_CAMPAIGNS = "FETCH_CAMPAIGNS";
export const CLEAR_CAMPAIGNS = "CLEAR_CAMPAIGNS";

export const FETCH_SETTINGS = "FETCH_SETTINGS";
export const CLEAR_SETTINGS = "CLEAR_SETTINGS";

export const FETCH_ANALYTICS = "FETCH_ANALYTICS";
export const CLEAR_ANALYTICS = "CLEAR_ANALYTICS";

export const FETCH_USERS = "FETCH_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
